# Generated by Django 3.2.7 on 2021-09-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, max_length=255),
        ),
    ]
